// -------------------------------------------------------------------
// Generated by 365admin-publish
// -------------------------------------------------------------------
/*
---
title: Page Info
---
*/
package cmds

import (
	"context"
	"encoding/json"
	"fmt"
	"os"
	"path"

	"github.com/365admin/sharepoint-governance/execution"
	"github.com/365admin/sharepoint-governance/schemas"
	"github.com/365admin/sharepoint-governance/utils"
)

func PageInfoPost(ctx context.Context, args []string) (*schemas.PageinfoResponse, error) {

	result, pwsherr := execution.ExecutePowerShell("john", "*", "sharepoint-governance", "30-sharepoint-page", "pageinfo.ps1", "", "-url", args[0])
	if pwsherr != nil {
		return nil, pwsherr
	}

	resultingFile := path.Join(utils.WorkDir("sharepoint-governance"), "pageinfo.response.json")
	data, err := os.ReadFile(resultingFile)
	if err != nil {
		return nil, err
	}
	resultObject := schemas.PageinfoResponse{}
	err = json.Unmarshal(data, &resultObject)
	if utils.Output == "json" {
		fmt.Println(string(data))
	}
	utils.PrintSkip2FirstAnd2LastLines(string(result))

	return nil, nil

}
