// -------------------------------------------------------------------
// Generated by 365admin-publish/api/20 makeschema.ps1
// -------------------------------------------------------------------
/*
---
title: Page Info
---
*/
package endpoints

import (
	"context"
	"encoding/json"
	"os"
	"path"

	"github.com/swaggest/usecase"

	"github.com/365admin/sharepoint-governance/execution"
	"github.com/365admin/sharepoint-governance/schemas"
	"github.com/365admin/sharepoint-governance/utils"
)

func PageInfoPost() usecase.Interactor {
	type Request struct {
		Url string `query:"url" binding:"required"`
	}
	u := usecase.NewInteractor(func(ctx context.Context, input Request, output *schemas.PageinfoResponse) error {

		_, err := execution.ExecutePowerShell("john", "*", "sharepoint-governance", "30-sharepoint-page", "pageinfo.ps1", "", "-url", input.Url)
		if err != nil {
			return err
		}

		resultingFile := path.Join(utils.WorkDir("sharepoint-governance"), "pageinfo.response.json")
		data, err := os.ReadFile(resultingFile)
		if err != nil {
			return err
		}
		resultObject := schemas.PageinfoResponse{}
		err = json.Unmarshal(data, &resultObject)
		*output = resultObject
		return err

	})
	u.SetTitle("Page Info")
	// u.SetExpectedErrors(status.InvalidArgument)
	u.SetTags("SharePoint Pages")
	return u
}
